name: Clarive Serverless Plugin
description: Execute a Serverless script. Associate server agent will execute the script for AWS.
version: 1.0
icon: https://github.com/clarive/cla-serverless-plugin/public/icon/serverless.svg
url: https://github.com/clarive/cla-serverless-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-serverless-plugin
